### ISSUE TITLE
fatal error LNK1181: cannot open input file 'flutter_engine.lib'

### ISSUE THREAD

**Issue by canewsin** [anlumo/flutter_embedder#3]
do we need to download these for linking from official repo?

**Comment by anlumo** [comment]
Yes. I'm working on automating this, but that script isn’t in this public repository yet.

**Comment by anlumo** [comment]
```
https://storage.googleapis.com/flutter_infra_release/flutter/{engine_version}/{platform_name}/{platform_name}-embedder.zip
```

Where `engine_version` is the commit hash of the engine (found in `$FLUTTER_HOME/bin/internal/engine.version`) and `platform_name` is `windows-x64` or `linux-x64` (macOS has a different naming scheme entirely).
